// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcfhbehfficqizdncgwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZmhiZWhmZmljcWl6ZG5jZ3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzY4NjMsImV4cCI6MjA2OTI1Mjg2M30.4b58TpR3JRwSJW1xtpdTx4DS9G9J-x0Q_MPcRQ2qeNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});